# Generated by ariadne-codegen
# Source: graphql/lldap-queries.graphql

from pydantic import Field

from .base_model import BaseModel


class AddTelegramIdAttribute(BaseModel):
    add_user_attribute: AddTelegramIdAttributeAddUserAttribute = Field(
        alias="addUserAttribute"
    )


class AddTelegramIdAttributeAddUserAttribute(BaseModel):
    ok: bool


AddTelegramIdAttribute.model_rebuild()
