# Generated by ariadne-codegen
# Source: graphql/lldap-queries.graphql

from pydantic import Field

from .base_model import BaseModel


class AddUserToGroup(BaseModel):
    add_user_to_group: AddUserToGroupAddUserToGroup = Field(alias="addUserToGroup")


class AddUserToGroupAddUserToGroup(BaseModel):
    ok: bool


AddUserToGroup.model_rebuild()
