# Generated by ariadne-codegen
# Source: graphql/lldap-queries.graphql

from pydantic import Field

from .base_model import BaseModel


class AddTelegramUsernameAttribute(BaseModel):
    add_user_attribute: AddTelegramUsernameAttributeAddUserAttribute = Field(
        alias="addUserAttribute"
    )


class AddTelegramUsernameAttributeAddUserAttribute(BaseModel):
    ok: bool


AddTelegramUsernameAttribute.model_rebuild()
