# Generated by ariadne-codegen
# Source: graphql/lldap-queries.graphql

from typing import Any

from .add_telegram_id_attribute import AddTelegramIdAttribute
from .add_telegram_username_attribute import AddTelegramUsernameAttribute
from .add_user_to_group import AddUserToGroup
from .async_base_client import AsyncBaseClient
from .create_group import CreateGroup
from .create_user import CreateUser
from .delete_group import DeleteGroup
from .delete_user import DeleteUser
from .get_user_by_id import GetUserById
from .get_user_by_telegram_username import GetUserByTelegramUsername
from .get_users_by_display_name import GetUsersByDisplayName
from .get_users_by_group import GetUsersByGroup
from .list_groups import ListGroups
from .list_users import ListUsers
from .remove_user_from_group import RemoveUserFromGroup
from .update_user import UpdateUser


def gql(q: str) -> str:
    return q


class Client(AsyncBaseClient):
    async def add_telegram_id_attribute(self, **kwargs: Any) -> AddTelegramIdAttribute:
        query = gql("""
            mutation AddTelegramIdAttribute {
              addUserAttribute(
                name: "telegramId"
                attributeType: STRING
                isList: false
                isVisible: true
                isEditable: true
              ) {
                ok
              }
            }
            """)
        variables: dict[str, object] = {}
        response = await self.execute(
            query=query,
            operation_name="AddTelegramIdAttribute",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return AddTelegramIdAttribute.model_validate(data)

    async def add_telegram_username_attribute(
        self, **kwargs: Any
    ) -> AddTelegramUsernameAttribute:
        query = gql("""
            mutation AddTelegramUsernameAttribute {
              addUserAttribute(
                name: "telegramUsername"
                attributeType: STRING
                isList: false
                isVisible: true
                isEditable: true
              ) {
                ok
              }
            }
            """)
        variables: dict[str, object] = {}
        response = await self.execute(
            query=query,
            operation_name="AddTelegramUsernameAttribute",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return AddTelegramUsernameAttribute.model_validate(data)

    async def list_users(self, **kwargs: Any) -> ListUsers:
        query = gql("""
            query ListUsers {
              users {
                ...UserFields
              }
            }

            fragment UserFields on User {
              id
              displayName
              email
              groups {
                id
                displayName
              }
              attributes {
                name
                value
              }
            }
            """)
        variables: dict[str, object] = {}
        response = await self.execute(
            query=query, operation_name="ListUsers", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return ListUsers.model_validate(data)

    async def get_user_by_id(self, id: str, **kwargs: Any) -> GetUserById:
        query = gql("""
            query GetUserById($id: String!) {
              user(userId: $id) {
                ...UserFields
              }
            }

            fragment UserFields on User {
              id
              displayName
              email
              groups {
                id
                displayName
              }
              attributes {
                name
                value
              }
            }
            """)
        variables: dict[str, object] = {"id": id}
        response = await self.execute(
            query=query, operation_name="GetUserById", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return GetUserById.model_validate(data)

    async def get_user_by_telegram_username(
        self, telegram_username: str, **kwargs: Any
    ) -> GetUserByTelegramUsername:
        query = gql("""
            query GetUserByTelegramUsername($telegramUsername: String!) {
              users(filters: {eq: {field: "telegramUsername", value: $telegramUsername}}) {
                ...UserFields
              }
            }

            fragment UserFields on User {
              id
              displayName
              email
              groups {
                id
                displayName
              }
              attributes {
                name
                value
              }
            }
            """)
        variables: dict[str, object] = {"telegramUsername": telegram_username}
        response = await self.execute(
            query=query,
            operation_name="GetUserByTelegramUsername",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return GetUserByTelegramUsername.model_validate(data)

    async def get_users_by_display_name(
        self, display_name: str, **kwargs: Any
    ) -> GetUsersByDisplayName:
        query = gql("""
            query GetUsersByDisplayName($displayName: String!) {
              users(filters: {eq: {field: "displayName", value: $displayName}}) {
                ...UserFields
              }
            }

            fragment UserFields on User {
              id
              displayName
              email
              groups {
                id
                displayName
              }
              attributes {
                name
                value
              }
            }
            """)
        variables: dict[str, object] = {"displayName": display_name}
        response = await self.execute(
            query=query,
            operation_name="GetUsersByDisplayName",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return GetUsersByDisplayName.model_validate(data)

    async def get_users_by_group(self, group: str, **kwargs: Any) -> GetUsersByGroup:
        query = gql("""
            query GetUsersByGroup($group: String!) {
              users(filters: {memberOf: $group}) {
                ...UserFields
              }
            }

            fragment UserFields on User {
              id
              displayName
              email
              groups {
                id
                displayName
              }
              attributes {
                name
                value
              }
            }
            """)
        variables: dict[str, object] = {"group": group}
        response = await self.execute(
            query=query, operation_name="GetUsersByGroup", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return GetUsersByGroup.model_validate(data)

    async def create_user(
        self,
        id: str,
        display_name: str,
        telegram_id: str,
        telegram_username: str,
        email: str,
        **kwargs: Any,
    ) -> CreateUser:
        query = gql("""
            mutation CreateUser($id: String!, $displayName: String!, $telegramId: String!, $telegramUsername: String!, $email: String!) {
              createUser(
                user: {id: $id, displayName: $displayName, email: $email, attributes: [{name: "telegramId", value: [$telegramId]}, {name: "telegramUsername", value: [$telegramUsername]}]}
              ) {
                ...UserFields
              }
            }

            fragment UserFields on User {
              id
              displayName
              email
              groups {
                id
                displayName
              }
              attributes {
                name
                value
              }
            }
            """)
        variables: dict[str, object] = {
            "id": id,
            "displayName": display_name,
            "telegramId": telegram_id,
            "telegramUsername": telegram_username,
            "email": email,
        }
        response = await self.execute(
            query=query, operation_name="CreateUser", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return CreateUser.model_validate(data)

    async def update_user(
        self,
        id: str,
        display_name: str,
        telegram_id: str,
        telegram_username: str,
        email: str,
        **kwargs: Any,
    ) -> UpdateUser:
        query = gql("""
            mutation UpdateUser($id: String!, $displayName: String!, $telegramId: String!, $telegramUsername: String!, $email: String!) {
              updateUser(
                user: {id: $id, displayName: $displayName, email: $email, insertAttributes: [{name: "telegramId", value: [$telegramId]}, {name: "telegramUsername", value: [$telegramUsername]}]}
              ) {
                ok
              }
            }
            """)
        variables: dict[str, object] = {
            "id": id,
            "displayName": display_name,
            "telegramId": telegram_id,
            "telegramUsername": telegram_username,
            "email": email,
        }
        response = await self.execute(
            query=query, operation_name="UpdateUser", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return UpdateUser.model_validate(data)

    async def delete_user(self, user_id: str, **kwargs: Any) -> DeleteUser:
        query = gql("""
            mutation DeleteUser($userId: String!) {
              deleteUser(userId: $userId) {
                ok
              }
            }
            """)
        variables: dict[str, object] = {"userId": user_id}
        response = await self.execute(
            query=query, operation_name="DeleteUser", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return DeleteUser.model_validate(data)

    async def list_groups(self, **kwargs: Any) -> ListGroups:
        query = gql("""
            query ListGroups {
              groups {
                id
                displayName
              }
            }
            """)
        variables: dict[str, object] = {}
        response = await self.execute(
            query=query, operation_name="ListGroups", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return ListGroups.model_validate(data)

    async def create_group(self, name: str, **kwargs: Any) -> CreateGroup:
        query = gql("""
            mutation CreateGroup($name: String!) {
              createGroup(name: $name) {
                id
              }
            }
            """)
        variables: dict[str, object] = {"name": name}
        response = await self.execute(
            query=query, operation_name="CreateGroup", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return CreateGroup.model_validate(data)

    async def delete_group(self, group_id: int, **kwargs: Any) -> DeleteGroup:
        query = gql("""
            mutation DeleteGroup($groupId: Int!) {
              deleteGroup(groupId: $groupId) {
                ok
              }
            }
            """)
        variables: dict[str, object] = {"groupId": group_id}
        response = await self.execute(
            query=query, operation_name="DeleteGroup", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return DeleteGroup.model_validate(data)

    async def add_user_to_group(
        self, user_id: str, group_id: int, **kwargs: Any
    ) -> AddUserToGroup:
        query = gql("""
            mutation AddUserToGroup($userId: String!, $groupId: Int!) {
              addUserToGroup(userId: $userId, groupId: $groupId) {
                ok
              }
            }
            """)
        variables: dict[str, object] = {"userId": user_id, "groupId": group_id}
        response = await self.execute(
            query=query, operation_name="AddUserToGroup", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return AddUserToGroup.model_validate(data)

    async def remove_user_from_group(
        self, user_id: str, group_id: int, **kwargs: Any
    ) -> RemoveUserFromGroup:
        query = gql("""
            mutation RemoveUserFromGroup($userId: String!, $groupId: Int!) {
              removeUserFromGroup(userId: $userId, groupId: $groupId) {
                ok
              }
            }
            """)
        variables: dict[str, object] = {"userId": user_id, "groupId": group_id}
        response = await self.execute(
            query=query,
            operation_name="RemoveUserFromGroup",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return RemoveUserFromGroup.model_validate(data)
