# Generated by ariadne-codegen
# Source: graphql/lldap-queries.graphql

from pydantic import Field

from .base_model import BaseModel
from .fragments import UserFields


class CreateUser(BaseModel):
    create_user: CreateUserCreateUser = Field(alias="createUser")


class CreateUserCreateUser(UserFields):
    pass


CreateUser.model_rebuild()
