# Generated by ariadne-codegen
# Source: graphql/lldap-queries.graphql

from pydantic import Field

from .base_model import BaseModel


class CreateGroup(BaseModel):
    create_group: CreateGroupCreateGroup = Field(alias="createGroup")


class CreateGroupCreateGroup(BaseModel):
    id: int


CreateGroup.model_rebuild()
