# Generated by ariadne-codegen
# Source: graphql/lldap-queries.graphql

from pydantic import Field

from .base_model import BaseModel


class DeleteUser(BaseModel):
    delete_user: DeleteUserDeleteUser = Field(alias="deleteUser")


class DeleteUserDeleteUser(BaseModel):
    ok: bool


DeleteUser.model_rebuild()
