# Generated by ariadne-codegen
# Source: graphql/lldap-queries.graphql

from pydantic import Field

from .base_model import BaseModel


class DeleteGroup(BaseModel):
    delete_group: DeleteGroupDeleteGroup = Field(alias="deleteGroup")


class DeleteGroupDeleteGroup(BaseModel):
    ok: bool


DeleteGroup.model_rebuild()
