# Generated by ariadne-codegen
# Source: graphql/lldap.graphql

from enum import Enum


class AttributeType(str, Enum):
    STRING = "STRING"
    INTEGER = "INTEGER"
    JPEG_PHOTO = "JPEG_PHOTO"
    DATE_TIME = "DATE_TIME"
