# Generated by ariadne-codegen
# Source: graphql/lldap-queries.graphql

from pydantic import Field

from .base_model import BaseModel


class UserFields(BaseModel):
    id: str
    display_name: str = Field(alias="displayName")
    email: str
    groups: list[UserFieldsGroups]
    attributes: list[UserFieldsAttributes]


class UserFieldsGroups(BaseModel):
    id: int
    display_name: str = Field(alias="displayName")


class UserFieldsAttributes(BaseModel):
    name: str
    value: list[str]


UserFields.model_rebuild()
