# Generated by ariadne-codegen
# Source: graphql/lldap-queries.graphql

from .base_model import BaseModel
from .fragments import UserFields


class GetUsersByGroup(BaseModel):
    users: list[GetUsersByGroupUsers]


class GetUsersByGroupUsers(UserFields):
    pass


GetUsersByGroup.model_rebuild()
