# Generated by ariadne-codegen
# Source: graphql/lldap-queries.graphql

from .base_model import BaseModel
from .fragments import UserFields


class GetUserByTelegramUsername(BaseModel):
    users: list[GetUserByTelegramUsernameUsers]


class GetUserByTelegramUsernameUsers(UserFields):
    pass


GetUserByTelegramUsername.model_rebuild()
