# Generated by ariadne-codegen
# Source: graphql/lldap-queries.graphql

from .base_model import BaseModel
from .fragments import UserFields


class GetUsersByDisplayName(BaseModel):
    users: list[GetUsersByDisplayNameUsers]


class GetUsersByDisplayNameUsers(UserFields):
    pass


GetUsersByDisplayName.model_rebuild()
