# Generated by ariadne-codegen
# Source: graphql/lldap-queries.graphql

from .base_model import BaseModel
from .fragments import UserFields


class GetUserById(BaseModel):
    user: GetUserByIdUser


class GetUserByIdUser(UserFields):
    pass


GetUserById.model_rebuild()
