# Generated by ariadne-codegen
# Source: graphql/lldap-queries.graphql

from .base_model import BaseModel
from .fragments import UserFields


class GetUsersByTelegramId(BaseModel):
    users: list[GetUsersByTelegramIdUsers]


class GetUsersByTelegramIdUsers(UserFields):
    pass


GetUsersByTelegramId.model_rebuild()
