# Generated by ariadne-codegen
# Source: graphql/lldap.graphql


from pydantic import Field

from .base_model import BaseModel


class AttributeValueInput(BaseModel):
    name: str
    "The name of the attribute. It must be present in the schema, and the type informs how\nto interpret the values."
    value: list[str]
    'The values of the attribute.\nIf the attribute is not a list, the vector must contain exactly one element.\nIntegers (signed 64 bits) are represented as strings.\nDates are represented as strings in RFC3339 format, e.g. "2019-10-12T07:20:50.52Z".\nJpegPhotos are represented as base64 encoded strings. They must be valid JPEGs.'


class CreateGroupInput(BaseModel):
    """The details required to create a group."""

    display_name: str = Field(alias="displayName")
    attributes: list[AttributeValueInput] | None = None
    "User-defined attributes."


class CreateUserInput(BaseModel):
    """The details required to create a user."""

    id: str
    email: str | None = None
    display_name: str | None = Field(alias="displayName", default=None)
    first_name: str | None = Field(alias="firstName", default=None)
    "First name of user. Deprecated: use attribute instead.\nIf both field and corresponding attribute is supplied, the attribute will take precedence."
    last_name: str | None = Field(alias="lastName", default=None)
    "Last name of user. Deprecated: use attribute instead.\nIf both field and corresponding attribute is supplied, the attribute will take precedence."
    avatar: str | None = None
    "Base64 encoded JpegPhoto. Deprecated: use attribute instead.\nIf both field and corresponding attribute is supplied, the attribute will take precedence."
    attributes: list[AttributeValueInput] | None = None
    "Attributes."


class EqualityConstraint(BaseModel):
    field: str
    value: str


class RequestFilter(BaseModel):
    """A filter for requests, specifying a boolean expression based on field constraints. Only one of
    the fields can be set at a time.
    """

    any: list[RequestFilter] | None = None
    all: list[RequestFilter] | None = None
    not_: RequestFilter | None = Field(alias="not", default=None)
    eq: EqualityConstraint | None = None
    member_of: str | None = Field(alias="memberOf", default=None)
    member_of_id: int | None = Field(alias="memberOfId", default=None)


class UpdateGroupInput(BaseModel):
    """The fields that can be updated for a group."""

    id: int
    "The group ID."
    display_name: str | None = Field(alias="displayName", default=None)
    "The new display name."
    remove_attributes: list[str] | None = Field(alias="removeAttributes", default=None)
    "Attribute names to remove.\nThey are processed before insertions."
    insert_attributes: list[AttributeValueInput] | None = Field(
        alias="insertAttributes", default=None
    )
    "Inserts or updates the given attributes.\nFor lists, the entire list must be provided."


class UpdateUserInput(BaseModel):
    """The fields that can be updated for a user."""

    id: str
    email: str | None = None
    display_name: str | None = Field(alias="displayName", default=None)
    first_name: str | None = Field(alias="firstName", default=None)
    "First name of user. Deprecated: use attribute instead.\nIf both field and corresponding attribute is supplied, the attribute will take precedence."
    last_name: str | None = Field(alias="lastName", default=None)
    "Last name of user. Deprecated: use attribute instead.\nIf both field and corresponding attribute is supplied, the attribute will take precedence."
    avatar: str | None = None
    "Base64 encoded JpegPhoto. Deprecated: use attribute instead.\nIf both field and corresponding attribute is supplied, the attribute will take precedence."
    remove_attributes: list[str] | None = Field(alias="removeAttributes", default=None)
    "Attribute names to remove.\nThey are processed before insertions."
    insert_attributes: list[AttributeValueInput] | None = Field(
        alias="insertAttributes", default=None
    )
    "Inserts or updates the given attributes.\nFor lists, the entire list must be provided."


CreateGroupInput.model_rebuild()
CreateUserInput.model_rebuild()
RequestFilter.model_rebuild()
UpdateGroupInput.model_rebuild()
UpdateUserInput.model_rebuild()
