# Generated by ariadne-codegen
# Source: graphql/lldap-queries.graphql

from pydantic import Field

from .base_model import BaseModel


class ListGroups(BaseModel):
    groups: list[ListGroupsGroups]


class ListGroupsGroups(BaseModel):
    id: int
    display_name: str = Field(alias="displayName")


ListGroups.model_rebuild()
