# Generated by ariadne-codegen
# Source: graphql/lldap-queries.graphql

from .base_model import BaseModel
from .fragments import UserFields


class ListUsers(BaseModel):
    users: list[ListUsersUsers]


class ListUsersUsers(UserFields):
    pass


ListUsers.model_rebuild()
