# Generated by ariadne-codegen
# Source: graphql/lldap-queries.graphql

from pydantic import Field

from .base_model import BaseModel


class RemoveUserFromGroup(BaseModel):
    remove_user_from_group: RemoveUserFromGroupRemoveUserFromGroup = Field(
        alias="removeUserFromGroup"
    )


class RemoveUserFromGroupRemoveUserFromGroup(BaseModel):
    ok: bool


RemoveUserFromGroup.model_rebuild()
