# Generated by ariadne-codegen
# Source: graphql/lldap-queries.graphql

from pydantic import Field

from .base_model import BaseModel


class UpdateUser(BaseModel):
    update_user: UpdateUserUpdateUser = Field(alias="updateUser")


class UpdateUserUpdateUser(BaseModel):
    ok: bool


UpdateUser.model_rebuild()
