from telethon.types import User

class NewMessage:
    def __init__(self, pattern: str) -> None: ...

    class Event:
        async def get_sender(self) -> User: ...
        async def respond(self, message: str) -> None: ...
