---
services:
  "tta-telegram-bot-dev":
    image: "nett/tta-telegram-bot:0.3.0"
    container_name: "telegram-bot-dev"
    volumes:
      - ../data:/app/data:rw

    env_file:
      - ../telegram.env

    ports:
      - "8002:8002"

    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:8002/health"]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 10s

    restart: always
...
