---
services:
  tta_telegram_bot:
    image: "nett/tta-telegram-bot:0.2.1"
    container_name: tta_telegram_bot
    volumes:
      - ../data:/app/data:rw
    env_file:
      - ../telegram.env
    ports:
      - "8002:8002"
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:8002/health"]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 10s
    restart: always
...
