# syntax=docker/dockerfile:1
FROM ubuntu:noble

RUN apt-get update -y \
    && apt-get upgrade -y \
    && apt-get install -y --no-install-recommends ca-certificates curl \
    && rm -Rf /var/lib/apt/lists/*

USER ubuntu:ubuntu
WORKDIR /app

RUN curl -LsSf https://astral.sh/uv/install.sh | sh
ENV PATH="/home/ubuntu/.local/bin/:$PATH"
ENV UV_PYTHON_INSTALL_DIR="/app/python"

COPY --chown=ubuntu:ubuntu pyproject.toml uv.lock README.md alembic.ini .
COPY --chown=ubuntu:ubuntu src/shared src/shared
COPY --chown=ubuntu:ubuntu src/control src/control
COPY --chown=ubuntu:ubuntu migrations migrations

RUN uv sync --extra control --no-dev --no-editable --frozen \
    && rm -Rf pyproject.toml uv.lock README.md src

ENV PATH="/app/.venv/bin:$PATH"

CMD ["control"]