import pathlib
from collections.abc import Callable, Coroutine

from telethon.events import NewMessage
from telethon.types import User

class TelegramClient:
    def __init__(
        self, session: str | pathlib.Path, api_id: int, api_hash: str
    ) -> None: ...
    async def connect(self) -> None: ...
    async def disconnect(self) -> None: ...
    async def sign_in(self, *, bot_token: str) -> None: ...
    async def run_until_disconnected(self) -> None: ...
    def on(
        self, event: NewMessage
    ) -> Callable[[Callable[..., Coroutine[object, object, None]]], None]: ...
    async def send_message(
        self, entity: int | str | User, message: str, *, parse_mode: str | None = None
    ) -> None: ...
