mutation AddTelegramIdAttribute {
  addUserAttribute(
    name: "telegramId"
    attributeType: STRING
    isList: false
    isVisible: true
    isEditable: true
  ) {
    ok
  }
}

fragment UserFields on User {
  id
  displayName
  groups {
    id
    displayName
  }
  attributes {
    name
    value
  }
}

query ListUsers {
  users {
    ...UserFields
  }
}

query GetUserById($id: String!) {
  user(userId: $id) {
    ...UserFields
  }
}

query GetUsersByTelegramId($telegramId: String!) {
  users(filters: { eq: { field: "telegramId", value: $telegramId } }) {
    ...UserFields
  }
}

query GetUsersByDisplayName($displayName: String!) {
  users(filters: { eq: { field: "displayName", value: $displayName } }) {
    ...UserFields
  }
}

query GetUsersByGroup($groupName: String!) {
  users(filters: { memberOf: $groupName }) {
    ...UserFields
  }
}

mutation CreateUser(
  $id: String!
  $telegramId: String!
  $displayName: String!
  $email: String!
) {
  createUser(
    user: {
      id: $id
      displayName: $displayName
      email: $email
      attributes: [{ name: "telegramId", value: [$telegramId] }]
    }
  ) {
    ...UserFields
  }
}

mutation UpdateUser(
  $id: String!
  $telegramId: String!
  $displayName: String!
  $email: String!
) {
  updateUser(
    user: {
      id: $id
      displayName: $displayName
      email: $email
      insertAttributes: [{ name: "telegramId", value: [$telegramId] }]
    }
  ) {
    ok
  }
}

mutation DeleteUser($userId: String!) {
  deleteUser(userId: $userId) {
    ok
  }
}

query ListGroups {
  groups {
    id
    displayName
  }
}

mutation CreateGroup($name: String!) {
  createGroup(name: $name) {
    id
  }
}

mutation DeleteGroup($groupId: Int!) {
  deleteGroup(groupId: $groupId) {
    ok
  }
}

mutation AddUserToGroup($userId: String!, $groupId: Int!) {
  addUserToGroup(userId: $userId, groupId: $groupId) {
    ok
  }
}

mutation RemoveUserFromGroup($userId: String!, $groupId: Int!) {
  removeUserFromGroup(userId: $userId, groupId: $groupId) {
    ok
  }
}
