"""Accounts."""

from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "434c9eea09b1"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "telegram_accounts",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=32), nullable=False),
        sa.Column("updated", sa.BigInteger(), nullable=False),
        sa.Column("meta", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_index(
        op.f("ix_telegram_accounts_meta"), "telegram_accounts", ["meta"], unique=False
    )
    op.create_table(
        "filebrowser_accounts",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=32), nullable=False),
        sa.Column("password", sa.String(length=60), nullable=False),
        sa.Column("notified", sa.Boolean(), nullable=False),
        sa.Column("updated", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "thelounge_accounts",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=32), nullable=False),
        sa.Column("password", sa.String(length=60), nullable=False),
        sa.Column("notified", sa.Boolean(), nullable=False),
        sa.Column("updated", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("telegram_accounts")
    op.drop_index(op.f("ix_telegram_accounts_meta"), table_name="telegram_accounts")
    op.drop_table("thelounge_accounts")
    op.drop_table("filebrowser_accounts")
    # ### end Alembic commands ###
